-- MySQL Script generated by MySQL Workbench
-- 12/13/16 11:30:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NotificacionesDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NotificacionesDB` ;

-- -----------------------------------------------------
-- Schema NotificacionesDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NotificacionesDB` DEFAULT CHARACTER SET utf8 ;
USE `NotificacionesDB` ;

-- -----------------------------------------------------
-- Table `NotificacionesDB`.`Credenciales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NotificacionesDB`.`Credenciales` ;

CREATE TABLE IF NOT EXISTS `NotificacionesDB`.`Credenciales` (
  `Usuario` VARCHAR(20) NOT NULL,
  `Contraseña` VARCHAR(200) NULL,
  `bActivo` INT NULL DEFAULT 1,
  PRIMARY KEY (`Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotificacionesDB`.`Notificador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NotificacionesDB`.`Notificador` ;

CREATE TABLE IF NOT EXISTS `NotificacionesDB`.`Notificador` (
  `Usuario` VARCHAR(20) NOT NULL,
  `idAlimento` INT NULL DEFAULT 0,
  `txtAlimento` VARCHAR(100) NULL,
  `idActividad` INT NULL DEFAULT 0,
  `txtActividad` VARCHAR(100) NULL,
  `idTexto` INT NULL DEFAULT 0,
  `txtTecto` VARCHAR(200) NULL,
  INDEX `Usuario_idx` (`Usuario` ASC),
  CONSTRAINT `Usuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `NotificacionesDB`.`Credenciales` (`Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `NotificacionesDB`.`Credenciales`
-- -----------------------------------------------------
START TRANSACTION;
USE `NotificacionesDB`;
INSERT INTO `NotificacionesDB`.`Credenciales` (`Usuario`, `Contraseña`, `bActivo`) VALUES ('Mizael', 'tecnotiv', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `NotificacionesDB`.`Notificador`
-- -----------------------------------------------------
START TRANSACTION;
USE `NotificacionesDB`;
INSERT INTO `NotificacionesDB`.`Notificador` (`Usuario`, `idAlimento`, `txtAlimento`, `idActividad`, `txtActividad`, `idTexto`, `txtTecto`) VALUES ('Mizael', 0, NULL, 1, 'Comida', 0, NULL);

COMMIT;

